# Generated by Django 2.2.3 on 2019-07-09 12:22

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, help_text='this is discount in precent', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='discount precentage')),
                ('record', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.URLField(help_text='put Partner website link here like : https://www.partner.com', verbose_name='Website')),
                ('desc', models.TextField(verbose_name='About Partner')),
                ('logo', models.ImageField(upload_to='partner/', verbose_name='Partner Logo')),
                ('field', models.CharField(max_length=200, verbose_name='Partner Field')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.IntegerField(choices=[(0, 'Repair and maintenance'), (1, 'consultation'), (2, 'installation of medical devices'), (3, 'Contact')], verbose_name='Service Type')),
                ('desc', models.TextField(verbose_name='about this service')),
                ('equipment', models.CharField(help_text='اسم الجهاز او النوع المطلوب له الخدمة', max_length=250)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to='Person/', verbose_name='Profile pic')),
                ('job', models.CharField(max_length=250, verbose_name='Job title')),
                ('organization', models.CharField(max_length=250, verbose_name='Organization')),
                ('about', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(help_text="you can add more than one number by Separate with '-' ", max_length=200)),
                ('Gender', models.BooleanField(choices=[(False, 'Male'), (True, 'Female')])),
                ('birthdate', models.DateField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic1', models.ImageField(upload_to='product/', verbose_name='Primary Product Image')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='secondary Product Image')),
                ('price', models.FloatField(help_text='this price in EGP')),
                ('desc', models.TextField(verbose_name='About Product')),
                ('video', models.URLField(blank=True, help_text='you should upload your video to youtube and provide the link here', null=True)),
                ('discount', models.IntegerField(default=0, help_text='this is discount in precent', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='discount precentage')),
                ('discount_exp_date', models.DateField(blank=True, help_text='this date is about when to end the discount', null=True, validators=[website.models.validate_date])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Partner')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Product')),
            ],
            options={
                'verbose_name': 'InvoiceItem',
                'verbose_name_plural': 'InvoiceItems',
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
