# Generated by Django 2.2.3 on 2019-07-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190721_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('profile', 'product')},
        ),
    ]
