# Generated by Django 2.2.3 on 2019-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190723_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'Repair & Maintenance'), (1, 'Consultation'), (2, 'Installation of medical devices'), (3, 'preparation of operating rooms and leisure'), (4, 'preparation Intensive care rooms ( ICU & CCU)'), (5, 'preparation of infant nursery centers'), (6, 'Construction of gas networks for hospitals'), (7, 'After-sales service'), (8, 'Preparation of Radiology Centers'), (9, 'Equipment outpatient clinics')], verbose_name='Service Type'),
        ),
    ]
