# Generated by Django 2.2.3 on 2019-08-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190729_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_val',
            new_name='property_value',
        ),
    ]
