# Generated by Django 2.2.3 on 2019-08-06 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190807_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='record',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
