# Generated by Django 2.2.3 on 2019-08-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20190809_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
