# Generated by Django 2.2.3 on 2019-08-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_invoice_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
