# Generated by Django 2.2.3 on 2019-08-18 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20190818_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='record',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
